version: '3'

services:
  db:
    image: hypriot/rpi-mysql:5.5
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - ./app/mysql:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mc_magic_mirror
      MYSQL_USER: root

  mcmagicmirror:
    build: .
    image: mcmagicmirror:latest
    ports:
      - "8000:8000"
    depends_on:
      - db