# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
