# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
